[build]
command = "npm run build"
output_directory = ".next"

[build.environment]
NODE_ENV = "production"
NEXT_PUBLIC_SUPABASE_URL = "dummy"  # Will be overridden in Cloudflare dashboard
NEXT_PUBLIC_SUPABASE_ANON_KEY = "dummy"  # Will be overridden in Cloudflare dashboard