[env.production]
vars = { ENVIRONMENT = "production" }

# Secrets that should be set in Cloudflare Dashboard:
# - NEXT_PUBLIC_SUPABASE_URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY
# - OPENROUTER_API_KEY
# - SUPABASE_SERVICE_ROLE_KEY